### ISSUE TITLE
UserWarning: Input image size (128*1000) doesn't match model (128*998)

### ISSUE THREAD

**Issue by IHateReptiloids** [kkoutini/passt_hear21#3]
I am trying to use PaSST model for finetuning and I am getting the following warning:
```
UserWarning: Input image size (128*1000) doesn't match model (128*998)
```
even though I apply model to audio clips of length of exactly 10 seconds. Is it the intended behaviour?
Another thing I am trying to figure out is how to apply model to shorter audio clips. For example, if the audio is 5 seconds long, I get a warning of the same type:
```
UserWarning: Input image size (128*500) doesn't match model (128*998)
```
Do I need to pad audio tensor in this case?

**Comment by kkoutini** [comment]
Hi! The warning is due to small preprocessing issue in the pre-trained weights and should have a minimal effect.
You don't need to pad your input. All the results in HEAR are produced using shorter audios.

**Comment by IHateReptiloids** [comment]
I see. Thanks for your reply!
