### ISSUE TITLE
Missing normalization in audio preprocessing

### ISSUE THREAD

**Issue by WhoCares96** [kkoutini/passt_hear21#8]
Hello,
thank you for your research! I am currently experimenting with the architecture and noticed that the [AugmentMelSTFT](https://github.com/kkoutini/passt_hear21/blob/main/hear21passt/models/preprocess.py#L15) preprocessor does have a ``norm`` member, suggesting that the processed audio data is being normalized. However, there is no normalization done during the forward step. 

Am I overseeing something here? Normalizing the input before training/inference seems to be reasonable to me.

Best regards!

**Comment by kkoutini** [comment]
Hi thank you!
yeah, you're right.  I dont remove DC component of the wave, I rembeber `torchaudio.compliance.kaldi.get_mel_banks` returns 0 for the first fft bin, so I think even if the wav form doesn't have a zero mean it shouldn't matter.
The wave files during training were normalized before mixing [here](https://github.com/kkoutini/PaSST/blob/4519e4605989b8c2e62dccb5b928af9bf7bf8602/audioset/dataset.py#L132C17-L132C17)

**Comment by WhoCares96** [comment]
Alright that makes sense, thank you for the explanation.
